feat: Spring boot 환경 구축
DEVTOPIA-KR/DEVTOPIA-BE pull request #1
Opened 2024-06-12 10:35 UTC by puleugo

주요 의존성은 다음과 같습니다.
- Kotlin: 1.9.24
- Spring boot: 3.3
- Gradle: 8.8
- JDK: 17

그 외에 이전 회의에서 언급되었던 `mockMvc`, `jackson`, `mockito` 등이 존재합니다.

2024-06-12 12:57 UTC, WhalesBob requested changes
리뷰 된 부분 체크 부탁드립니다~

2024-06-12 12:57 UTC, WhalesBob commented on src/test/kotlin/com/devtopia/community/CommunityApplicationTests.kt
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
MockMVC 사용하는데 RANDOM_PORT 주신 이유가 궁금합니다

2024-06-12 12:57 UTC, WhalesBob commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3312/devtopia
application-prod.properties 로 바꿔서 올려주시고, 로컬 부분은 gitignore 에 넣어서 관리하는것도 좋을 것 같아요! 혹시 히스토리 자체에서 application.properties 빼는 법 아시면 그대로 진행해 주세요.

2024-06-12 12:57 UTC, WhalesBob commented on docker-compose.yml
> +      MYSQL_PASSWORD: passwd
도커 컴포즈 요거 개인적으로 사용하시는건가요? 아니면 배포 타겟팅일까요?

2024-06-12 13:08 UTC, puleugo commented on src/test/kotlin/com/devtopia/community/CommunityApplicationTests.kt
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
어노테이션 설명만 읽었을 때는 실제 서버랑 유사하게 작업하려고 했었는데, MockMvc를 사용하니 큰 차이가 없겠네요. Mock으로 변경하겠습니다~

2024-06-12 13:18 UTC, puleugo commented on docker-compose.yml
> +      MYSQL_PASSWORD: passwd
후자입니다. 서버 계정 막 받은 시점이기에 환경변수 작업 안하고 바로 올렸습니다.
추후에 이전 회의에서 얘기나왔던 github secret으로 env 값 넣어주면 될 것 같네용.

2024-06-12 13:20 UTC, puleugo commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3312/devtopia
형상관리 고려해서 prod로 복제하고 gitignore에 추가하겠습니다~

2024-06-12 14:05 UTC, puleugo commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3312/devtopia
변경했습니다. 대화 닫겠습니다~ [544da89](https://github.com/DEVTOPIA-KR/DEVTOPIA-BE/pull/1/commits/544da897fb1fdcb787d49ecf7758dcc2e1d1f754)

2024-06-12 14:05 UTC, puleugo commented on src/test/kotlin/com/devtopia/community/CommunityApplicationTests.kt
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
변경했습니당~ [4a3b5ff](https://github.com/DEVTOPIA-KR/DEVTOPIA-BE/pull/1/commits/4a3b5ff17d3fd53c20401ad9d07a64caedcb9d12)

2024-06-13 04:15 UTC, WhalesBob approved these changes

2024-06-13 04:15 UTC, merged